
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.15.0
 * Query Engine version: 85179d7826409ee107a6ba334b5e305ae3fba9fb
 */
Prisma.prismaVersion = {
  client: "6.15.0",
  engine: "85179d7826409ee107a6ba334b5e305ae3fba9fb"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.PacienteScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  dni: 'dni',
  direccion: 'direccion',
  telefono: 'telefono',
  email: 'email',
  fechaNac: 'fechaNac',
  obraSocial: 'obraSocial',
  createdAt: 'createdAt'
};

exports.Prisma.ArmazonScalarFieldEnum = {
  id: 'id',
  marca: 'marca',
  modelo: 'modelo',
  codigo: 'codigo',
  stock: 'stock',
  costo: 'costo',
  precioFinal: 'precioFinal',
  createdAt: 'createdAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.VidrioScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  descripcion: 'descripcion',
  precioCal: 'precioCal',
  precioRanura: 'precioRanura',
  precioPerforado: 'precioPerforado',
  precioCalFinal: 'precioCalFinal',
  precioRanuraFinal: 'precioRanuraFinal',
  precioPerforadoFinal: 'precioPerforadoFinal',
  activo: 'activo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RecetaScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  pacienteId: 'pacienteId',
  armazonId: 'armazonId',
  vidrioId: 'vidrioId',
  distancia: 'distancia',
  odEsf: 'odEsf',
  odCil: 'odCil',
  odEje: 'odEje',
  oiEsf: 'oiEsf',
  oiCil: 'oiCil',
  oiEje: 'oiEje',
  distancia2: 'distancia2',
  od2Esf: 'od2Esf',
  od2Cil: 'od2Cil',
  od2Eje: 'od2Eje',
  oi2Esf: 'oi2Esf',
  oi2Cil: 'oi2Cil',
  oi2Eje: 'oi2Eje',
  tratamiento: 'tratamiento',
  formato: 'formato',
  dip: 'dip',
  fechaReceta: 'fechaReceta',
  doctor: 'doctor',
  patologia: 'patologia',
  obs: 'obs',
  montaje: 'montaje',
  sena: 'sena',
  laboratorio: 'laboratorio',
  precioArmazon: 'precioArmazon',
  precioVidrio: 'precioVidrio',
  total: 'total',
  estadoPago: 'estadoPago',
  montoPagado: 'montoPagado',
  metodoPago: 'metodoPago',
  entregaFecha: 'entregaFecha',
  entregada: 'entregada',
  entregadaAt: 'entregadaAt',
  avisoRetiroEnviado: 'avisoRetiroEnviado',
  avisoRetiroEnviadoAt: 'avisoRetiroEnviadoAt',
  retirada: 'retirada',
  retiradaAt: 'retiradaAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.FotoRecetaScalarFieldEnum = {
  id: 'id',
  recetaId: 'recetaId',
  foto: 'foto',
  observaciones: 'observaciones',
  createdAt: 'createdAt'
};

exports.Prisma.EvolucionRefraccionScalarFieldEnum = {
  id: 'id',
  pacienteId: 'pacienteId',
  fecha: 'fecha',
  distancia: 'distancia',
  odEsf: 'odEsf',
  odCil: 'odCil',
  odEje: 'odEje',
  oiEsf: 'oiEsf',
  oiCil: 'oiCil',
  oiEje: 'oiEje',
  tratamiento: 'tratamiento',
  formato: 'formato',
  dip: 'dip',
  montaje: 'montaje',
  doctor: 'doctor',
  patologia: 'patologia',
  obs: 'obs',
  createdAt: 'createdAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.FotoEvolucionScalarFieldEnum = {
  id: 'id',
  evolucionId: 'evolucionId',
  foto: 'foto',
  observaciones: 'observaciones',
  createdAt: 'createdAt'
};

exports.Prisma.ServicioOpticaScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  precio: 'precio',
  activo: 'activo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ConfiguracionScalarFieldEnum = {
  id: 'id',
  seniaPorcentaje: 'seniaPorcentaje',
  descuentoEfectivo: 'descuentoEfectivo',
  descuentoDebito: 'descuentoDebito',
  descuentoTransferencia: 'descuentoTransferencia',
  cuotasCreditoJson: 'cuotasCreditoJson',
  updatedAt: 'updatedAt',
  createdAt: 'createdAt'
};

exports.Prisma.ProveedorScalarFieldEnum = {
  id: 'id',
  tipo: 'tipo',
  nombre: 'nombre',
  telefono: 'telefono',
  email: 'email',
  productos: 'productos',
  contactoPreferido: 'contactoPreferido',
  formasPago: 'formasPago',
  frecuenciaEntrega: 'frecuenciaEntrega',
  observaciones: 'observaciones',
  banco: 'banco',
  cbu: 'cbu',
  alias: 'alias',
  titular: 'titular',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MovimientoProveedorScalarFieldEnum = {
  id: 'id',
  proveedorId: 'proveedorId',
  fecha: 'fecha',
  concepto: 'concepto',
  debe: 'debe',
  haber: 'haber',
  saldo: 'saldo',
  createdAt: 'createdAt'
};

exports.Prisma.CategoriaGastoScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  color: 'color',
  activo: 'activo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.GastoScalarFieldEnum = {
  id: 'id',
  categoriaId: 'categoriaId',
  descripcion: 'descripcion',
  monto: 'monto',
  recurrente: 'recurrente',
  frecuenciaMeses: 'frecuenciaMeses',
  fechaVenc: 'fechaVenc',
  pagado: 'pagado',
  pagadoAt: 'pagadoAt',
  obs: 'obs',
  codigoCliente: 'codigoCliente',
  numeroPago: 'numeroPago',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CuentaScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  medioPago: 'medioPago',
  saldoInicial: 'saldoInicial',
  activo: 'activo',
  orden: 'orden',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CajaDiariaScalarFieldEnum = {
  id: 'id',
  fecha: 'fecha',
  saldoInicial: 'saldoInicial',
  cerrada: 'cerrada',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MovimientoCajaScalarFieldEnum = {
  id: 'id',
  cajaDiariaId: 'cajaDiariaId',
  cuentaId: 'cuentaId',
  tipo: 'tipo',
  concepto: 'concepto',
  monto: 'monto',
  medioPago: 'medioPago',
  refId: 'refId',
  refTipo: 'refTipo',
  createdAt: 'createdAt'
};

exports.Prisma.DetallePagoScalarFieldEnum = {
  id: 'id',
  refId: 'refId',
  refTipo: 'refTipo',
  medioPago: 'medioPago',
  monto: 'monto',
  createdAt: 'createdAt'
};

exports.Prisma.TurnoScalarFieldEnum = {
  id: 'id',
  fecha: 'fecha',
  duracion: 'duracion',
  pacienteId: 'pacienteId',
  nombrePaciente: 'nombrePaciente',
  telefono: 'telefono',
  motivo: 'motivo',
  notas: 'notas',
  estado: 'estado',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.TipoProveedor = exports.$Enums.TipoProveedor = {
  ARMAZONES: 'ARMAZONES',
  VIDRIOS: 'VIDRIOS'
};

exports.Prisma.ModelName = {
  Paciente: 'Paciente',
  Armazon: 'Armazon',
  Vidrio: 'Vidrio',
  Receta: 'Receta',
  FotoReceta: 'FotoReceta',
  EvolucionRefraccion: 'EvolucionRefraccion',
  FotoEvolucion: 'FotoEvolucion',
  ServicioOptica: 'ServicioOptica',
  Configuracion: 'Configuracion',
  Proveedor: 'Proveedor',
  MovimientoProveedor: 'MovimientoProveedor',
  CategoriaGasto: 'CategoriaGasto',
  Gasto: 'Gasto',
  Cuenta: 'Cuenta',
  CajaDiaria: 'CajaDiaria',
  MovimientoCaja: 'MovimientoCaja',
  DetallePago: 'DetallePago',
  Turno: 'Turno'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
