ALTER TABLE "Receta" ADD COLUMN "distancia2" TEXT;
ALTER TABLE "Receta" ADD COLUMN "od2Esf" REAL;
ALTER TABLE "Receta" ADD COLUMN "od2Cil" REAL;
ALTER TABLE "Receta" ADD COLUMN "od2Eje" REAL;
ALTER TABLE "Receta" ADD COLUMN "oi2Esf" REAL;
ALTER TABLE "Receta" ADD COLUMN "oi2Cil" REAL;
ALTER TABLE "Receta" ADD COLUMN "oi2Eje" REAL;
